name: Bug Report
description: Report a bug in Kore Memory
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill in the details below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Start the server with `kore`
        2. Send a POST request to /save with ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or tracebacks if available.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Kore Memory Version
      description: "Run: python -c \"import kore_memory; print(kore_memory.__version__)\""
      placeholder: "e.g. 0.7.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: "Run: python --version"
      placeholder: "e.g. 3.12.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows (WSL)
        - Windows (native)
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      description: Paste any relevant log output or Python traceback.
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, config, etc.).
