name: Feature Request
description: Suggest a new feature or improvement for Kore Memory
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this feature solve? Is this related to a frustration?
      placeholder: I'm always frustrated when ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the project does this relate to?
      options:
        - Core (memory storage, search, decay)
        - API / Endpoints
        - Python SDK (KoreClient)
        - JS/TS SDK
        - MCP Server
        - Dashboard
        - LangChain / CrewAI Integration
        - Documentation
        - CI/CD / Tooling
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Important — I have a workaround
        - Critical — blocking my use case

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, code snippets, mockups, or references.
