"""
Kore — Storage Protocol
Abstract interface for memory storage backends.
Current implementation: SQLite (via repository.py)
Future: PostgreSQL, etc.
"""

from __future__ import annotations
from typing import Protocol
from .models import MemoryRecord, MemorySaveRequest, MemoryUpdateRequest


class MemoryStore(Protocol):
    """Interface for memory storage backends."""

    def save(self, req: MemorySaveRequest, agent_id: str) -> tuple[int, int]: ...
    def save_batch(self, reqs: list[MemorySaveRequest], agent_id: str) -> list[tuple[int, int]]: ...
    def search(self, query: str, limit: int, category: str | None, semantic: bool, agent_id: str) -> list[MemoryRecord]: ...
    def delete(self, memory_id: int, agent_id: str) -> bool: ...
    def update(self, memory_id: int, req: MemoryUpdateRequest, agent_id: str) -> bool: ...
    def get_timeline(self, subject: str, limit: int, agent_id: str) -> list[MemoryRecord]: ...
    def export(self, agent_id: str) -> list[dict]: ...
    def import_records(self, records: list[dict], agent_id: str) -> int: ...
    def run_decay_pass(self, agent_id: str | None) -> int: ...
    def cleanup_expired(self, agent_id: str | None) -> int: ...
    def add_tags(self, memory_id: int, tags: list[str], agent_id: str) -> int: ...
    def get_tags(self, memory_id: int, agent_id: str) -> list[str]: ...
    def remove_tags(self, memory_id: int, tags: list[str], agent_id: str) -> int: ...
    def search_by_tag(self, tag: str, agent_id: str, limit: int) -> list[MemoryRecord]: ...
    def add_relation(self, source_id: int, target_id: int, relation: str, agent_id: str) -> bool: ...
    def get_relations(self, memory_id: int, agent_id: str) -> list[dict]: ...
